#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
#EXPOSE 80
#EXPOSE 443
EXPOSE 9093
EXPOSE 6102

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Example.UserService.API/Example.UserService.API.csproj", "Example.UserService.API/"]
COPY ["Example.Common/Example.Common.csproj", "Example.Common/"]
RUN dotnet restore "Example.UserService.API/Example.UserService.API.csproj"
COPY . .
WORKDIR "/src/Example.UserService.API"
RUN dotnet build "Example.UserService.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Example.UserService.API.csproj" -c Release -o /app/publish
RUN rm /app/publish/appsettings.Init.json

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

#Timezone
RUN apt-get update ;\
    apt-get install -y tzdata
ENV TZ=Asia/Ho_Chi_Minh

ENTRYPOINT ["dotnet", "Example.UserService.API.dll", "--environment=Staging"]