<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<UserSecretsId>0b929f10-5f66-471f-bbfd-50cfd9d72ae3</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="logs\**" />
		<Content Remove="logs\**" />
		<None Remove="logs\**" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="logs\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.27.1" />
		<PackageReference Include="EPPlus" Version="8.6.0" />
		<PackageReference Include="Grpc.Tools" Version="2.63.0" PrivateAssets="All" />

		<PackageReference Include="FirebaseAdmin" Version="2.4.0" />
		<PackageReference Include="MassTransit" Version="8.0.16" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.0.16" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.5">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.5" />

		
	</ItemGroup>
	<ItemGroup>
			<None Include="appsettings.Init.json">
				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			</None>
		</ItemGroup>

		<ItemGroup>
			<Folder Include="Middlewares\" />
		</ItemGroup>

		<ItemGroup>
		  <ProjectReference Include="..\Example.Common\Example.Common.csproj" />
		</ItemGroup>


</Project>
